baseURL: https://notes.daltonmiller.me
languageCode: en-us
title: Dalton's Notes
#theme: Docsy

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-FSTZRCJFNC

module:
  proxy: direct
  hugoVersion:
    extended: true
    min: "0.73.0"
  imports:
    - path: github.com/google/docsy
    - path: github.com/google/docsy/dependencies

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  offlineSearch: true
  algolia_docsearch: false